# Generated by Django 5.2.17 on 2026-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "slug")},
        ),
    ]
