# Generated by Django 5.2.17 on 2026-08-16 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "budget_type",
                    models.CharField(
                        choices=[("FIXED", "Fixed Price"), ("HOURLY", "Hourly Rate")],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                (
                    "min_budget",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                (
                    "max_budget",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("REMOTE", "Remote"), ("ONSITE", "On-Site")],
                        default="REMOTE",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open for Proposals"),
                            ("REVIEWING", "Under Review"),
                            ("ASSIGNED", "Assigned / In Contract"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("proposals_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_freelancer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="categories.category",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills_required",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="profiles.skill"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="categories.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="project_attachments/"
                    ),
                ),
                ("file_url", models.CharField(blank=True, max_length=500, null=True)),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
