# Generated by Django 5.2.17 on 2026-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
