# Generated by Django 5.2.17 on 2026-08-16 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(default="Bengaluru, India", max_length=100),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("projects_posted_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Senior Full Stack Developer & UI Designer",
                        max_length=150,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                ("experience_years", models.IntegerField(default=3)),
                ("location", models.CharField(default="Mumbai, India", max_length=100)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time (40+ hrs/wk)"),
                            ("PART_TIME", "Part Time (< 30 hrs/wk)"),
                            ("AS_NEEDED", "As Needed"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("completed_projects_count", models.IntegerField(default=0)),
                (
                    "response_rate",
                    models.IntegerField(default=98, help_text="Percentage e.g. 98%"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freelancers",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma separated e.g. React, Django, PostgreSQL",
                        max_length=255,
                    ),
                ),
                ("project_url", models.URLField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="profiles.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_time_days", models.IntegerField(default=3)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="profiles.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="categories.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="INTERMEDIATE", max_length=20)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.freelancerprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profiles.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("freelancer", "skill")},
            },
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="skills",
            field=models.ManyToManyField(
                related_name="freelancers",
                through="profiles.FreelancerSkill",
                to="profiles.skill",
            ),
        ),
    ]
